services:
  containerguard-agent:
    build: ./
    image: containerguard:latest
    container_name: containerguard-agent
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ruser/.kube/config:/root/.kube/config:ro
      - /home/ruser/containerguard-v2/data:/app/data
      - /home/ruser/containerguard-v2/backend/src/config.yaml:/app/config.yaml:ro
    environment:
      - KUBECONFIG=/root/.kube/config
    restart: unless-stopped
    networks:
      - containerguard-net
networks:
  containerguard-net:
    driver: bridge
